### ISSUE TITLE
assertBodyEndsWith: aString

### ISSUE THREAD

**Issue by hhzl** [herby/silk#9] opened 2015-03-04 04:13 UTC
The following test fails

````
testDivContainerWithButtons
	| s |

	s := '#fixture' asSilk.
	s:= s DIV: {'id' -> 'container'}.
	(s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].
	(s BUTTON: 'hello2') on: 'click' bind: [Transcript show: 'Hello2'].
	(s BUTTON: 'hello3') on: 'click' bind: [Transcript show: 'Hello3'].
	
	Transcript show: document body innerHTML.
	self assertBodyEndsWith: '>sentinel<div id="container"><button>hello1</button><button>hello2</button><button>hello3</button></div></div>'.
````

To make it work I have to change the last line to

````
self assertBodyEndsWith: '>sentinel<divid="container"><button>hello1</button><button>hello2</button><button>hello3</button></div></div>'.
````

The problem is with the space method ``assertBodyEndsWith`` eliminates.

This method is a copy of the method used in domite.

**Comment by hhzl** [comment] 2015-03-04 09:20
https://github.com/herby/silk/pull/8 (4 tests) contains a workaround to make 2 tests work.

**Comment by herby** [comment] 2015-03-04 09:29
It's not a bug, it's a feature. So whitespaces are ignored. Closing.

**Comment by herby** [comment] 2015-03-04 09:30
Do you _need_ the id? I don't see the need for it in the test code... of course if it is use later, ok.

**Closed by herby** 2015-03-04 09:29 UTC

**Comment by hhzl** [comment] 2015-03-04 10:09
Yes, I need ``id``s and ``class`` attributes in elements produced by Silk. And I want a test which tests against _working_ HTML code.
